name: Build and Deploy Docker Images

on:
  push:
    branches:
      - main

jobs:
  build_and_push_frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image for frontend
        working-directory: ./app
        run: docker build -t luuyifei/scalagos-capstone:latest .

      - name: Push Docker image for frontend to Docker Registry
        run: docker push luuyifei/scalagos-capstone:latest

  build_and_push_backend:
    runs-on: ubuntu-latest
    needs: build_and_push_frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image for backend
        working-directory: ./server
        run: docker build --build-arg ATLAS_URI="${{ secrets.MONGODB_URI }}" -t luuyifei/scalagos-capstone-backend:latest .

      - name: Push Docker image for backend to Docker Registry
        run: docker push luuyifei/scalagos-capstone-backend:latest

      - name: Trigger Render Deployment
        if: ${{ secrets.RENDER_DEPLOY_HOOK != '' }}
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}