name: Build and Deploy Docker Images

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Registry
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push frontend image
        working-directory: ./app
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/scalagos-capstone:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/scalagos-capstone:latest

      - name: Build and push backend image
        working-directory: ./server
        run: |
          docker build --build-arg ATLAS_URI="${{ secrets.MONGODB_URI }}" -t ${{ secrets.DOCKER_USERNAME }}/scalagos-capstone-backend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/scalagos-capstone-backend:latest
